[package]
name = "lzscr-parser"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
lzscr-ast = { path = "../lzscr-ast", version = "0.1.0" }
lzscr-lexer = { path = "../lzscr-lexer", version = "0.1.0" }
lzscr-preast = { path = "../lzscr-preast", version = "0.1.0" }
thiserror = "2"
